### ISSUE TITLE
pluralize.plural('person') doesn't work.

### ISSUE THREAD

**Issue by i-kapri** [plurals/pluralize#174]
Hi!

I have installed your package for my angular project and have imported it in one of my files as follows:

`import * as Pluralize from 'typescript-pluralize';` 

After that I have written somewhere in my code: `const plural = Pluralize.default.plural('Person')`.
Then I see that the value of the constant `plural` is `/(pe)(?:rson|ople)$/i,$1opleople`.

Could someone tell me why this regex does not pluralize the string above?

Thank you in advance!

Kind Regards
Kapri

**Comment by blakeembrey** [comment]
`typescript-pluralize` is not this package, but rather looks like someone took the contents of this package and repackaged it without license attribution. You can file an issue on that repos issue tracker instead.

**Comment by i-kapri** [comment]
Firstly, I would like to thank you Mr. @blakeembrey for your immediate response.

May I ask, can I use your package `pluralize` in typescript without `require('pluralize')` ?

For example like this: `import * as pluralize from 'pluralize';`.

Thank you for your answer!

Kind Regards
Kapri

**Comment by blakeembrey** [comment]
I would recommend reading about how to use packages with TypeScript generally since this isn’t the right place to help people understand TypeScript. That said, you can install the community maintained types from https://www.npmjs.com/package/@types/pluralize.
