### ISSUE TITLE
Plural of 'by' is 'bys', got 'bies'

### ISSUE THREAD

**Issue by amitbeck** [plurals/pluralize#181]
When I run the following, it returns "bies". AFAIK the correct pluralization of "by" is "bys".

```js
pluralize("by") // => "bies"

pluralize("Added by") // => "Added bies"
```

**Comment by blakeembrey** [comment]
Thanks for the report. I'm going to keep this package limited to largely nouns though, since it'd require a lot more work to understand the entire English language and that might be better by just re-using some dictionary.
