### ISSUE TITLE
Preserve case

### ISSUE THREAD

**Issue by Tobbe** [plurals/pluralize#184]
Hi

We use this library to automatically provide plural and singular forms of data model names.

Typical input would be
`User` -> `Users`
`Posts` -> `Post`
`Comment` -> `Comments`
etc

Those all work great

Problem is with multi-word model names where we need to provide our own rules, like `UserNews`. "News" is the same in singular and plural. So in our use case we need to make up a plural form. So we do `pluralize.addIrregularRule('UserNews', 'UserNewses')`. However, now when we do `pluralize('UserNews')` we get `'Usernewses'`. For us it's important to keep the casing of all letters as they are. Our models are case sensitive. So we need the plural in this case to be `UserNewses`.

I found a related issue at #131 and PR at #136 but nothing has unfortunately come out of them yet.

@blakeembrey I'm happy to work on a PR this weekend if you can provide some guidance on how you want this solved.

**Comment by blakeembrey** [comment]
This doesn’t sound so much like you want to preserve case as you want this library to actually understand that `UserNews` is two words and apply the pluralization as if the suffix is “news”? This sounds out-of-scope for the library and pretty difficult to achieve. If you have a specific format, I’d suggest giving it the parts you want to pluralize and then formatting it back yourself.

**Comment by blakeembrey** [comment]
> I noticed you had tests for both PascalCase and camelCase

IIRC that was more around keeping the casing and not supporting pluralization, but it's a good flag. I'll probably look at eliminating some of that logic since it causes a lot of confusion for people.

**Comment by Tobbe** [comment]
@blakeembrey Thanks for your input in this thread. I'll close this issue now as what I want to do is out of scope for `pluralize` and is much better handled by the consumer of your library (i.e. my own app)

Thanks for creating and maintaining this library!

**Comment by arossert** [comment]
I also had this issue now that I'm trying to add a rule, it looks like 
```
pluralize.addSingularRule('record', 'feedRecord');
```
But the output is all lowercase

```
pluralize.addSingularRule('record', 'feedRecord');
console.log(pluralize.singular('record'));
```
The output is `feedrecord` and not `feedRecord`, is this expected?
