### ISSUE TITLE
Add a pluralize.if(string, boolean)

### ISSUE THREAD

**Issue by flexa-david** [plurals/pluralize#196]
Does this feature exist? If I created it would it be merged?

Easier than having to go cats.length > 1 ? pluralize('cat') : 'cat'
It'd just be pluralize.if('cat', cats.length > 1)

**Comment by blakeembrey** [comment]
No, you can just do `pluralize('cat', cats.length)` already.

**Comment by blakeembrey** [comment]
Alternatively, if your concern is around the unclarity of knowing the input string is already singular we could make that explicit in a future version.
